### ISSUE TITLE
Select a Stack

### ISSUE THREAD

**Issue by mattbatman** [CivicCode/uReport-client#1]
We started to discuss this already, but we should all agree on what, if any, JavaScript and CSS frameworks and build tools we're going to use. This could include:

- React vs. "vanilla"
- Bootstrap vs. nothing
- CSS/post-css vs. Sass vs. Less
- webpack vs. create-react-app
- to eslint or not
- npm vs. yarn

I know that David had mentioned yesterday that he felt like React seemed like overkill.

Dana and I didn't want to introduce Bootstrap or a heavy CSS framework.

**Comment by dpalazz** [comment]
I agree that using React can make it easier to render a different component
for the different form variants we will need; however, that's also because
I'm not as comfortable with vanilla! I'd be fine either way, though. It
would be good practice for me to use vanilla again, but I'd probably be
quicker using React.
